webtalk_init -webtalk_dir /home/maja/Digital/projs/VivadoProjs/LED_WALKING/LED_WALKING.sim/sim_1/behav/xsim/xsim.dir/testbench_arcade_check_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep 20 11:09:11 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "019d1761-1c37-49dd-8cce-72bf3fae8bed" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "36de296d0a4543b5befd88aa0e0f022f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4147.340 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "29.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "241178865 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "7.79_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115216_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2171602391 -regid "" -xml /home/maja/Digital/projs/VivadoProjs/LED_WALKING/LED_WALKING.sim/sim_1/behav/xsim/xsim.dir/testbench_arcade_check_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/maja/Digital/projs/VivadoProjs/LED_WALKING/LED_WALKING.sim/sim_1/behav/xsim/xsim.dir/testbench_arcade_check_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/maja/Digital/projs/VivadoProjs/LED_WALKING/LED_WALKING.sim/sim_1/behav/xsim/xsim.dir/testbench_arcade_check_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
